# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/y2qdcmw/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter y2qdcmw,$(TARGET_DEVICE)),)

endif
