# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/y2qdcmw/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/y2qdcmw

# Audio
PRODUCT_COPY_FILES += \
    vendor/samsung/y2qdcmw/proprietary/vendor/etc/LVACFS_Configuration.txt:$(TARGET_COPY_OUT_VENDOR)/etc/LVACFS_Configuration.txt \
    vendor/samsung/y2qdcmw/proprietary/vendor/etc/LVACFS_ControlParams.txt:$(TARGET_COPY_OUT_VENDOR)/etc/LVACFS_ControlParams.txt \
    vendor/samsung/y2qdcmw/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/samsung/y2qdcmw/proprietary/vendor/etc/floating_feature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/floating_feature.xml

# Bluetooth
PRODUCT_COPY_FILES += \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/bcm4375B1_murata.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4375B1_murata.hcd \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/bcmdhd_clm.blob:$(TARGET_COPY_OUT_VENDOR)/firmware/bcmdhd_clm.blob \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/bcmdhd_mfg.bin_b1:$(TARGET_COPY_OUT_VENDOR)/firmware/bcmdhd_mfg.bin_b1 \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/bcmdhd_mon.bin_b1:$(TARGET_COPY_OUT_VENDOR)/firmware/bcmdhd_mon.bin_b1 \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/bcmdhd_sta.bin_b1:$(TARGET_COPY_OUT_VENDOR)/firmware/bcmdhd_sta.bin_b1

# Camera
PRODUCT_COPY_FILES += \
    vendor/samsung/y2qdcmw/proprietary/vendor/lib/hw/camera.qcom.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.qcom.so \
    vendor/samsung/y2qdcmw/proprietary/vendor/lib/hw/com.qti.chi.override.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/com.qti.chi.override.so \
    vendor/samsung/y2qdcmw/proprietary/vendor/lib/libvdis_interface.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvdis_interface.so \
    vendor/samsung/y2qdcmw/proprietary/vendor/lib64/hw/camera.qcom.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/camera.qcom.so \
    vendor/samsung/y2qdcmw/proprietary/vendor/lib64/hw/com.qti.chi.override.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/com.qti.chi.override.so \
    vendor/samsung/y2qdcmw/proprietary/vendor/lib64/libvdis_interface.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvdis_interface.so

# Firmware
PRODUCT_COPY_FILES += \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/cs35l40-bot-dsp1-spk-prot-calib.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l40-bot-dsp1-spk-prot-calib.bin \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/cs35l40-bot-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l40-bot-dsp1-spk-prot.bin \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/cs35l40-bot-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l40-bot-dsp1-spk-prot.wmfw \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/cs35l40-rcv-dsp1-spk-prot-calib.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l40-rcv-dsp1-spk-prot-calib.bin \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/cs35l40-rcv-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l40-rcv-dsp1-spk-prot.bin \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/cs35l40-rcv-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l40-rcv-dsp1-spk-prot.wmfw \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/cs40l20.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l20.bin

# Graphics
PRODUCT_COPY_FILES += \
    vendor/samsung/y2qdcmw/proprietary/vendor/etc/qdcm_calib_data_ss_dsi_panel_S6E3HAB_AMB677TY01_WQHD.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_ss_dsi_panel_S6E3HAB_AMB677TY01_WQHD.xml

# NFC
PRODUCT_COPY_FILES += \
    vendor/samsung/y2qdcmw/proprietary/vendor/etc/sec_senn82ab_rfreg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/sec_senn82ab_rfreg.bin \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/sec_senn82ab_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sec_senn82ab_firmware.bin

# Sensors
PRODUCT_COPY_FILES += \
    vendor/samsung/y2qdcmw/proprietary/vendor/etc/sensors/config/kona_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kona_ak991x_0.json \
    vendor/samsung/y2qdcmw/proprietary/vendor/etc/sensors/config/kona_ak991x_4.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kona_ak991x_4.json \
    vendor/samsung/y2qdcmw/proprietary/vendor/etc/sensors/config/kona_ak991x_13.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kona_ak991x_13.json

# Wi-Fi
PRODUCT_COPY_FILES += \
    vendor/samsung/y2qdcmw/proprietary/vendor/etc/wifi/indoorchannel.info:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/indoorchannel.info \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/nvram.txt_1rh_es11_b0:$(TARGET_COPY_OUT_VENDOR)/firmware/nvram.txt_1rh_es11_b0 \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/nvram.txt_1rh_es12_b0:$(TARGET_COPY_OUT_VENDOR)/firmware/nvram.txt_1rh_es12_b0 \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/nvram.txt_1rh_es13_b0:$(TARGET_COPY_OUT_VENDOR)/firmware/nvram.txt_1rh_es13_b0 \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/nvram.txt_1rh_es32_b0:$(TARGET_COPY_OUT_VENDOR)/firmware/nvram.txt_1rh_es32_b0 \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/nvram.txt_1rh_es41_b1:$(TARGET_COPY_OUT_VENDOR)/firmware/nvram.txt_1rh_es41_b1 \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/nvram.txt_1rh_es42_b1:$(TARGET_COPY_OUT_VENDOR)/firmware/nvram.txt_1rh_es42_b1 \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/nvram.txt_1rh_es43_b1:$(TARGET_COPY_OUT_VENDOR)/firmware/nvram.txt_1rh_es43_b1 \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/nvram.txt_CS01_semco_b1:$(TARGET_COPY_OUT_VENDOR)/firmware/nvram.txt_CS01_semco_b1 \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/nvram.txt_ES00_semco_b0:$(TARGET_COPY_OUT_VENDOR)/firmware/nvram.txt_ES00_semco_b0 \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/nvram.txt_ES01_semco_b0:$(TARGET_COPY_OUT_VENDOR)/firmware/nvram.txt_ES01_semco_b0 \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/nvram.txt_ES02_semco_b0:$(TARGET_COPY_OUT_VENDOR)/firmware/nvram.txt_ES02_semco_b0 \
    vendor/samsung/y2qdcmw/proprietary/vendor/firmware/nvram.txt_ES03_semco_b0:$(TARGET_COPY_OUT_VENDOR)/firmware/nvram.txt_ES03_semco_b0

PRODUCT_PACKAGES += \
    lib_SamsungRec_08020 \
    lib_lvacfs \
    librecordalive \
    libswdap \
    libsec-ril
